// AUTO-GENERATED by scripts/generate-academy-titles.mjs
// Do not edit manually — run `npm run generate:academy-titles` to refresh.
// Runs automatically via the `predev` and `prebuild` npm scripts.

export type AcademyTitleName =
  | 'about-academy'
  | 'about-us'
  | 'academy-students'
  | 'current-training-programs'
  | 'footer'
  | 'mission-and-values'
  | 'our-goals'
  | 'our-results'
  | 'our-sponsors'
  | 'protez-academy'
  | 'special-thanks-to-all-our-partners'
  | 'summit'
  | 'summit-results'
  | 'we-train'
  | 'welcome'
  | 'yakov-gradinar'

export type AcademyTitleDimensions = { width: number; height: number }

export type AcademyTitleEntry = {
  base: AcademyTitleName
  alt: string
  desktop: { en: AcademyTitleDimensions; uk: AcademyTitleDimensions }
  mobile: { en: AcademyTitleDimensions; uk: AcademyTitleDimensions }
}

export const ACADEMY_TITLES: Record<AcademyTitleName, AcademyTitleEntry> = {
  'about-academy': {
    base: 'about-academy',
    alt: 'about-academy',
    desktop: { en: { width: 458, height: 149 }, uk: { width: 458, height: 141 } },
    mobile: { en: { width: 269, height: 92 }, uk: { width: 267, height: 88 } },
  },
  'about-us': {
    base: 'about-us',
    alt: 'about-us',
    desktop: { en: { width: 390, height: 73 }, uk: { width: 390, height: 81 } },
    mobile: { en: { width: 225, height: 43 }, uk: { width: 225, height: 47 } },
  },
  'academy-students': {
    base: 'academy-students',
    alt: 'academy-students',
    desktop: { en: { width: 284, height: 92 }, uk: { width: 265, height: 92 } },
    mobile: { en: { width: 491, height: 149 }, uk: { width: 458, height: 148 } },
  },
  'current-training-programs': {
    base: 'current-training-programs',
    alt: 'current-training-programs',
    desktop: { en: { width: 436, height: 142 }, uk: { width: 523, height: 146 } },
    mobile: { en: { width: 299, height: 139 }, uk: { width: 303, height: 90 } },
  },
  footer: {
    base: 'footer',
    alt: 'footer',
    desktop: { en: { width: 635, height: 165 }, uk: { width: 635, height: 165 } },
    mobile: { en: { width: 325, height: 92 }, uk: { width: 325, height: 92 } },
  },
  'mission-and-values': {
    base: 'mission-and-values',
    alt: 'mission-and-values',
    desktop: { en: { width: 286, height: 92 }, uk: { width: 263, height: 99 } },
    mobile: { en: { width: 495, height: 149 }, uk: { width: 455, height: 161 } },
  },
  'our-goals': {
    base: 'our-goals',
    alt: 'our-goals',
    desktop: { en: { width: 313, height: 160 }, uk: { width: 535, height: 167 } },
    mobile: { en: { width: 177, height: 89 }, uk: { width: 306, height: 99 } },
  },
  'our-results': {
    base: 'our-results',
    alt: 'our-results',
    desktop: { en: { width: 387, height: 142 }, uk: { width: 323, height: 91 } },
    mobile: { en: { width: 224, height: 89 }, uk: { width: 581, height: 147 } },
  },
  'our-sponsors': {
    base: 'our-sponsors',
    alt: 'our-sponsors',
    desktop: { en: { width: 500, height: 142 }, uk: { width: 407, height: 161 } },
    mobile: { en: { width: 289, height: 89 }, uk: { width: 235, height: 99 } },
  },
  'protez-academy': {
    base: 'protez-academy',
    alt: 'protez-academy',
    desktop: { en: { width: 458, height: 141 }, uk: { width: 458, height: 141 } },
    mobile: { en: { width: 265, height: 88 }, uk: { width: 265, height: 88 } },
  },
  'special-thanks-to-all-our-partners': {
    base: 'special-thanks-to-all-our-partners',
    alt: 'special-thanks-to-all-our-partners',
    desktop: { en: { width: 705, height: 218 }, uk: { width: 870, height: 216 } },
    mobile: { en: { width: 303, height: 188 }, uk: { width: 312, height: 187 } },
  },
  summit: {
    base: 'summit',
    alt: 'summit',
    desktop: { en: { width: 571, height: 193 }, uk: { width: 571, height: 193 } },
    mobile: { en: { width: 353, height: 161 }, uk: { width: 353, height: 161 } },
  },
  'summit-results': {
    base: 'summit-results',
    alt: 'summit-results',
    desktop: { en: { width: 397, height: 236 }, uk: { width: 535, height: 236 } },
    mobile: { en: { width: 329, height: 160 }, uk: { width: 330, height: 160 } },
  },
  'we-train': {
    base: 'we-train',
    alt: 'we-train',
    desktop: { en: { width: 274, height: 140 }, uk: { width: 542, height: 141 } },
    mobile: { en: { width: 159, height: 87 }, uk: { width: 313, height: 88 } },
  },
  welcome: {
    base: 'welcome',
    alt: 'welcome',
    desktop: { en: { width: 319, height: 154 }, uk: { width: 301, height: 154 } },
    mobile: { en: { width: 584, height: 234 }, uk: { width: 554, height: 234 } },
  },
  'yakov-gradinar': {
    base: 'yakov-gradinar',
    alt: 'yakov-gradinar',
    desktop: { en: { width: 607, height: 149 }, uk: { width: 598, height: 161 } },
    mobile: { en: { width: 281, height: 92 }, uk: { width: 274, height: 99 } },
  },
}
