export enum AcademyIDs {
  Intro = 'academyIntro',
  OurGoals = 'ourGoals',
  Academy = 'academy',
  OurResults = 'ourResults',
  OurTeachers = 'ourTeachers',
  Chief = 'chief',
  TheoryLectures = 'theoryLectures',
  PracticeSessions = 'practiceSessions',
  PastAndUpcomingEvents = 'pastAndUpcomingEvents',
  AcademyStudents = 'academyStudents',
  AmputeeRehab = 'amputeeRehab',
  SummitResults = 'summitResults',
  WeAreInNews = 'weAreInNews',
  SpecialThanksToAllOurPartners = 'specialThanksToAllOurPartners',
  Footer = 'footer',
}

export enum ProtezIDs {
  LetsGiveHope = 'letsGiveHope',
  PeopleTrustUs = 'peopleTrustUs',
  ProstheticsForUkrainians = 'prostheticsForUkrainians',
  InNeed = 'inNeed',
  OurResults = 'ourResults',
  SampleProsthesesCosts = 'sampleProsthesesCosts',
  ProtezAcademy = 'protezAcademy',
  Veterans = 'veterans',
  Events = 'events',
  PressRelease = 'pressRelease',
  OurPatients = 'ourPatients',
  MeetOurTeam = 'meetOurTeam',
  OfficeLocations = 'officeLocations',
  SpecialThanksToAllOurPartners = 'specialThanksToAllOurPartners',
  OurStarSupporters = 'ourStarSupporters',
  MailingList = 'mailingList',
  Merch = 'merch',
  Footer = 'footer',
}
