export enum ProtezIDs {
  LetsGiveHope = 'letsGiveHope',
  PeopleTrustUs = 'peopleTrustUs',
  ProstheticsForUkrainians = 'prostheticsForUkrainians',
  InNeed = 'inNeed',
  OurResults = 'ourResults',
  SampleProsthesesCosts = 'sampleProsthesesCosts',
  ProtezAcademy = 'protezAcademy',
  Veterans = 'veterans',
  Events = 'events',
  PressRelease = 'pressRelease',
  OurPatients = 'ourPatients',
  MeetOurTeam = 'meetOurTeam',
  OfficeLocations = 'officeLocations',
  SpecialThanksToAllOurPartners = 'specialThanksToAllOurPartners',
  OurStarSupporters = 'ourStarSupporters',
  MailingList = 'mailingList',
  Merch = 'merch',
  Footer = 'footer',
}
